<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=1920, height=1080">
<!-- Generated by build.py. Edit this template, not index.html. -->
<script src="./gsap.min.js"></script>
<style>
  @font-face { font-family: 'SceneSans'; src: local('Segoe UI Variable Display'), local('Segoe UI Variable'), local('Segoe UI'); font-weight: 100 900; }
  * { box-sizing: border-box; }
  html, body { margin: 0; width: 1920px; height: 1080px; overflow: hidden; }
  body { background: #090b0c; color: #f3f5f8; font-family: 'SceneSans', sans-serif; }
  #card { position: relative; width: 1920px; height: 1080px;
    background: radial-gradient(ellipse 1150px 700px at 50% 46%, #171c1b 0%, #0d1010 53%, #090b0c 100%); }
  .statement { position: absolute; left: 170px; top: 0; width: 1580px; height: 970px;
    display: flex; align-items: center; justify-content: center; text-align: center;
    font-size: 54px; line-height: 1.27; font-weight: 620; letter-spacing: -0.018em;
    opacity: 0; padding: 0 35px; }
  .statement span { max-width: 1510px; }
  #line5 { font-size: 86px; font-weight: 620; letter-spacing: -0.025em; }
  #line5 .brand { color: #8fe3d4; }
  #line6 { position: absolute; bottom: 70px; width: 100%; text-align: center;
    color: #c1c8c5; font-size: 30px; font-weight: 550; letter-spacing: 0.025em; opacity: 0; }
</style>
</head>
<body>
<main id="card" data-composition-id="title" data-width="1920" data-height="1080" data-fps="30" data-duration="20">
  <div id="line1" class="statement"><span>We built iTantra so you can reach people over long distances, even with no cell network.</span></div>
  <div id="line2" class="statement"><span>Speak in any of 10 languages, and your message is read aloud on the other side.</span></div>
  <div id="line3" class="statement"><span>It travels phone to phone, through the people around you, across {DISTANCE} of campus.</span></div>
  <div id="line4" class="statement"><span>No towers. No internet. No new hardware. Just the phones people already carry.</span></div>
  <div id="line5" class="statement"><span><span class="brand">iTantra.</span> Speak. Send. Be heard.</span></div>
  <div id="line6">Team chmod 777 · Team ID 148903 · NIE Mysuru</div>
</main>
<audio id="ticks" src="./assets/title_sfx.wav" data-start="0" data-duration="20" preload="auto"></audio>
<script>
  // Only one statement occupies the centre at a time. The final identity gets a longer hold.
  const tl = gsap.timeline({ paused: true });
  const starts = [0.6, 4.0, 7.4, 10.8, 14.5];
  starts.forEach((start, i) => {
    const target = '#line' + (i + 1);
    tl.fromTo(target, { opacity: 0, y: 12 },
      { opacity: 1, y: 0, duration: 0.6, ease: 'power2.out' }, start);
    if (i < 4) {
      tl.to(target, { opacity: 0, duration: 0.35, ease: 'power1.in' }, starts[i + 1] - 0.35);
    }
  });
  tl.fromTo('#line6', { opacity: 0, y: 6 },
    { opacity: 1, y: 0, duration: 0.6, ease: 'power2.out' }, 14.5);
  tl.to({}, { duration: 0.01 }, 19.99);
  window.__timelines = window.__timelines || {};
  window.__timelines['title'] = tl;
  tl.seek(0);
</script>
</body>
</html>
