<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=1920, height=1080">
<!-- Generated by build.py from this template. -->
<script src="./gsap.min.js"></script>
<style>
  @font-face { font-family: 'SceneSans'; src: local('Segoe UI Variable Display'), local('Segoe UI Variable'), local('Segoe UI'); font-weight: 100 900; }
  * { box-sizing: border-box; }
  html, body { margin: 0; width: 1920px; height: 1080px; overflow: hidden; }
  body { background: #090b0c; color: #f3f5f8; font-family: 'SceneSans', sans-serif; }
  #card { position: relative; width: 1920px; height: 1080px;
    background: radial-gradient(ellipse 1350px 800px at 38% 48%, #141918 0%, #0c0f0f 57%, #090b0c 100%); }
  #rule { position: absolute; left: 255px; top: 275px; width: 2px; height: 500px;
    background: #8fe3d4; opacity: 0.62; }
  .statement { position: absolute; left: 330px; top: 245px; width: 1270px; height: 570px;
    display: flex; align-items: center; text-align: left; font-size: 62px;
    line-height: 1.23; font-weight: 600; letter-spacing: -0.017em; opacity: 0; }
  #line5 { font-size: 91px; line-height: 1.15; letter-spacing: -0.032em; font-weight: 630; }
  #line5 .brand { display: block; color: #8fe3d4; font-size: 125px; margin-bottom: 14px; }
  #line6 { position: absolute; left: 330px; bottom: 74px; color: #c1c8c5;
    font-size: 29px; font-weight: 540; letter-spacing: 0.018em; opacity: 0; }
</style>
</head>
<body>
<main id="card" data-composition-id="title_b" data-width="1920" data-height="1080" data-fps="30" data-duration="20">
  <div id="rule"></div>
  <div id="line1" class="statement"><span>We built iTantra so you can reach people over long distances, even with no cell network.</span></div>
  <div id="line2" class="statement"><span>Speak in any of 10 languages, and your message is read aloud on the other side.</span></div>
  <div id="line3" class="statement"><span>It travels phone to phone, through the people around you, across {DISTANCE} of campus.</span></div>
  <div id="line4" class="statement"><span>No towers. No internet. No new hardware. Just the phones people already carry.</span></div>
  <div id="line5" class="statement"><span><span class="brand">iTantra.</span>Speak. Send. Be heard.</span></div>
  <div id="line6">Team chmod 777 · Team ID 148903 · NIE Mysuru</div>
</main>
<script>
  const tl = gsap.timeline({ paused: true });
  const starts = [0.6, 4.0, 7.4, 10.8, 14.5];
  starts.forEach((start, i) => {
    const target = '#line' + (i + 1);
    tl.fromTo(target, { opacity: 0, y: 10 },
      { opacity: 1, y: 0, duration: 0.6, ease: 'power2.out' }, start);
    if (i < 4) {
      tl.to(target, { opacity: 0, duration: 0.35, ease: 'power1.in' }, starts[i + 1] - 0.35);
    }
  });
  tl.fromTo('#line6', { opacity: 0, y: 6 },
    { opacity: 1, y: 0, duration: 0.6, ease: 'power2.out' }, 14.5);
  tl.to({}, { duration: 0.01 }, 19.99);
  window.__timelines = window.__timelines || {};
  window.__timelines['title_b'] = tl;
  tl.seek(0);
</script>
</body>
</html>
