/* Scene 2 v3a: node build.js [--prepare|--audio-only|--preview|--render]. */
const fs=require('fs'),path=require('path'),cp=require('child_process');
const HERE=__dirname,REPO=path.resolve(HERE,'../../..'),M=JSON.parse(fs.readFileSync(path.join(REPO,'machine.local.json')));
const ROOT=M.footage_root,RENDERS=M.renders_dir,OUT=path.join(path.resolve(REPO,process.env.S2A_RENDER_ROOT||RENDERS),'scene2/v3a'),A=path.join(HERE,'assets');
const FPS=30,SR=48000,YASH_REPLY=process.env.YASH_REPLY==='true',args=new Set(process.argv.slice(2)),preview=args.has('--preview');
const slots=JSON.parse(fs.readFileSync(path.join(HERE,'slots.json'))),ttsFile=path.join(RENDERS,'tts_itantra/tts_msg.wav');
const need=(ok,msg)=>{if(!ok)throw Error(msg)},mkdir=p=>fs.mkdirSync(p,{recursive:true});
function run(exe,argv,cwd=REPO){const x=cp.spawnSync(exe,argv.map(String),{cwd,encoding:'utf8',shell:exe.endsWith('.cmd'),maxBuffer:64*1024*1024});need(!x.error&&x.status===0,`${exe}: ${x.error||''}\n${x.stderr||''}\n${x.stdout||''}`);return x.stdout;}
function info(p){need(fs.existsSync(p),`Missing asset: ${p}`);return JSON.parse(run('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_type,width,height','-of','json',p]));}
function video(p,len,portrait=false){const x=info(p),v=x.streams.find(s=>s.codec_type==='video');need(v&&Number(x.format.duration)+.08>=len&&v.width>=100&&v.height>=100&&(!portrait||v.height>v.width),`Bad video: ${p}`);return v;}
function fresh(p,s){return !fs.existsSync(p)||s.some(x=>fs.statSync(x).mtimeMs>fs.statSync(p).mtimeMs)}
function link(src,dst){mkdir(path.dirname(dst));if(fs.existsSync(dst))fs.unlinkSync(dst);try{fs.linkSync(src,dst)}catch{fs.copyFileSync(src,dst)}}
function still(src,dst,at,filter){if(fresh(dst,[src]))run('ffmpeg',['-v','error','-y','-ss',at,'-i',src,...(filter?['-vf',filter]:[]),'-frames:v','1','-q:v','3',dst]);}
function grade(){return fs.readFileSync(path.join(REPO,'film/scene1/grades.sh'),'utf8').match(/^GRADE_V1="(.*)"$/m)[1]}
function camera(file,out,len){const src=path.join(ROOT,'Video',file),dst=path.join(A,out);need(fs.existsSync(src),`Missing footage ${file}`);if(fresh(dst,[src,path.join(REPO,'film/scene1/grades.sh')]))run('ffmpeg',['-v','error','-y','-ss','0','-t',len,'-i',src,'-vf',`fps=30,scale=1920:1080:flags=lanczos,${grade()},format=yuv420p`,'-an','-c:v','libx264','-preset','fast','-crf','20','-movflags','+faststart',dst]);video(dst,len);return dst;}
function walk(){const src=path.join(ROOT,'Video/normalpart2.mp4'),ramp=path.join(REPO,'results/T0006/ramp.json'),dst=path.join(A,'walk.mp4');need(fs.existsSync(src)&&fs.existsSync(ramp),'Missing walk source or ramp');const pieces=JSON.parse(fs.readFileSync(ramp)).pieces;
  if(fresh(dst,[src,ramp,path.join(REPO,'film/scene1/grades.sh')])){const fc=pieces.map((p,i)=>`[0:v]trim=start=${p.src_start}:end=${p.src_end},setpts=(PTS-STARTPTS)/${p.speed},fps=30,scale=1920:1080,setsar=1[v${i}]`);fc.push(pieces.map((_,i)=>`[v${i}]`).join('')+`concat=n=${pieces.length}:v=1:a=0,${grade()},format=yuv420p[out]`);run('ffmpeg',['-v','error','-y','-i',src,'-filter_complex',fc.join(';'),'-map','[out]','-frames:v','180','-an','-c:v','libx264','-preset','fast','-crf','20',dst]);}
  video(dst,5.95);return {span:pieces.reduce((n,p)=>n+p.src_end-p.src_start,0),pieces};}
function slot(spec,name){need(spec.path.startsWith('RENDERS:'),'Slot must use RENDERS:');const rel=spec.path.slice(8).split('/');need(!rel.some(s=>s==='..'||s==='')&&!path.isAbsolute(rel.join('/')),'Unsafe slot path');const src=path.join(RENDERS,...rel),dst=path.join(A,name+'.mp4');need(fs.existsSync(src)||preview,`Missing required slot: ${spec.path}`);if(fs.existsSync(src)){video(src,spec.duration,true);if(!fs.existsSync(dst)||fs.statSync(dst).size!==fs.statSync(src).size)link(src,dst)}else run('ffmpeg',['-v','error','-y','-f','lavfi','-i',`color=c=0x101820:s=1080x2290:r=30:d=${spec.duration}`,'-an','-c:v','libx264','-preset','ultrafast',dst]);const v=video(dst,spec.duration,true);still(dst,path.join(A,name+'_first.jpg'),0);still(dst,path.join(A,name+'_last.jpg'),spec.duration-.08);return {video:`assets/${name}.mp4`,width:Math.round(1000*v.width/v.height),placeholder:!fs.existsSync(src)};}
function timeline(tts,w){const seg=[],add=(name,start,end,extra={})=>seg.push({name,start:+start.toFixed(3),end:+end.toFixed(3),...extra});
  add('card_out',0,1.6);add('bench',1.6,5.9,{source:'FOOTAGE:Video/normalpart1.mp4',source_in:0,source_out:4.3});add('vachana_split_in',5.9,6.4,{source:'FOOTAGE:Video/normalpart1.mp4',source_in:4.3,source_out:4.8});
  const vs=6.4,send=vs+slots.vachana_send.sent_at,ws=send+.4,over=ws+6,yash=over+5,ya=yash+2.65;
  add('vachana_send',vs,send,{slot:'vachana_send',slot_in:0,slot_out:slots.vachana_send.sent_at,camera_source:'FOOTAGE:Video/normalpart1.mp4',camera_offset:4.8,camera_visible_until:vs+6.03});add('send_fly',send,send+.8,{slot:'vachana_send',sent_at:+send.toFixed(3)});
  add('walk',ws,over,{source:'FOOTAGE:Video/normalpart2.mp4',source_ranges:w.pieces.map(p=>[p.src_start,p.src_end]),speed_factor:+(w.span/6).toFixed(3),overlap_with_flight:.4});add('overhead',over,yash,{walk_transition:.6});
  add('yash_before_notification',yash,ya,{source:'FOOTAGE:Video/normalpart6.mp4',source_in:0,source_out:2.65});const ye=ya+(YASH_REPLY?slots.yash_app.duration:slots.yash_app.play_at+.15+tts+.6);
  add('yash_app',ya,ye,{slot:'yash_app',slot_in:0,slot_out:+(ye-ya).toFixed(3),camera_source:'FOOTAGE:Video/normalpart6.mp4',camera_early:[2.65,7.1],camera_reply:YASH_REPLY?[7.1,12.647]:null});
  const width=Math.round(1000*1080/2400);return {fps:FPS,duration:+ye.toFixed(3),segments:seg,narration_starts:{N1:+(ws+.3).toFixed(3)},slot_fields:{vachana_send:slots.vachana_send,yash_app:slots.yash_app},YASH_REPLY,end_state:{slot:'yash_app',slot_time:+(ye-ya-1/FPS).toFixed(3),position:{x:(1920-width)/2,y:40,width,height:1000},background:'#0a0d12'}};}
function captions(T,tts){const p=path.join(REPO,'film/captions/v3/s2a.json');mkdir(path.dirname(p));const by=Object.fromEntries(T.segments.map(s=>[s.name,s])),ya=by.yash_app.start,ns=T.narration_starts.N1,ttsAt=ya+slots.yash_app.play_at+.15;
  const c=[{start:6.482,end:9.802,text:"Hey dude, I'm in the campus\nnear the entry benches,"},{start:9.802,end:11.062,text:'where are you?'},{start:ns,end:ns+1.55,text:"Let's see how far that message"},{start:ns+1.55,end:ns+3.14,text:'actually has to travel.'},{start:by.yash_before_notification.start+1.31,end:by.yash_before_notification.start+2.85,text:"It's too hot here."},{start:ttsAt,end:ttsAt+tts*.55,text:"Hey dude, I'm in the campus\nnear the entry benches,"},{start:ttsAt+tts*.55,end:ttsAt+tts,text:'where are you?'}];
  if(YASH_REPLY)c.push({start:ya+12.11,end:ya+14.57,text:"I'm in the garden.\nI'll come to you."});const clean=c.map(x=>({start:+x.start.toFixed(3),end:+Math.min(x.end,T.duration).toFixed(3),text:x.text}));fs.writeFileSync(p,JSON.stringify(clean,null,2)+'\n');return clean;}
function prepare(){mkdir(A);mkdir(OUT);const b=camera('normalpart1.mp4','bench.mp4',10.83),y=camera('normalpart6.mp4','yash.mp4',12.647),w=walk();const app={vachana_send:slot(slots.vachana_send,'vachana_send'),yash_app:slot(slots.yash_app,'yash_app')};
  still(b,path.join(A,'bench_start.jpg'),0);still(y,path.join(A,'yash_first.jpg'),0);still(path.join(A,'walk.mp4'),path.join(A,'walk_last.jpg'),5.96);still(path.join(A,'vachana_send.mp4'),path.join(A,'message_crop.jpg'),11.75,'crop=960:440:60:650');still(path.join(A,'vachana_send.mp4'),path.join(A,'vachana_sent.jpg'),12.8);
  const kit=path.join(REPO,'film/common/glass');if(fs.existsSync(path.join(kit,'glass.css'))){mkdir(path.join(A,'glass'));for(const f of ['glass.css','glass.js','noise.png'])if(fs.existsSync(path.join(kit,f)))fs.copyFileSync(path.join(kit,f),path.join(A,'glass',f));}
  if(fs.existsSync(path.join(HERE,'overhead/overhead.js'))){const geo=path.join(REPO,'film/scene2/geo'),osm=path.join(geo,'nie_north_osm.json'),outlines=path.join(geo,'campus_outlines.json');need(fs.existsSync(osm)&&fs.existsSync(outlines),'Missing overhead campus geometry');fs.writeFileSync(path.join(A,'geo.js'),'window.OVERHEAD_GEO='+JSON.stringify({osm:JSON.parse(fs.readFileSync(osm)),outlines:JSON.parse(fs.readFileSync(outlines))})+';\n');}
  return {app,w,speed:Math.round(w.span/6),glass:fs.existsSync(path.join(A,'glass/glass.css')),overhead:fs.existsSync(path.join(HERE,'overhead/overhead.js'))};}
function page(T,P,c){let html=fs.readFileSync(path.join(HERE,'index.html.tpl'),'utf8');const ya=T.segments.find(s=>s.name==='yash_app'),subs={TIMELINE:JSON.stringify(T),SLOTS:JSON.stringify(P.app),CAPTIONS:JSON.stringify(c),DURATION:T.duration,SPEED:P.speed,Y_APP_DUR:+(ya.end-ya.start).toFixed(3),REPLY_VIDEO:T.YASH_REPLY?'<video id="yReply" class="clip" src="assets/yash.mp4" data-start="43.53" data-duration="5.547" data-media-start="7.1" muted playsinline></video>':'',GLASS_LINK:P.glass?'<link rel="stylesheet" href="assets/glass/glass.css">':'',OVERHEAD_LINK:P.overhead?'<link rel="stylesheet" href="overhead/overhead.css"><script src="assets/geo.js"></script><script src="overhead/overhead.js"></script>':''};for(const [k,v] of Object.entries(subs))html=html.replaceAll('{{'+k+'}}',String(v));need(!/\{\{[A-Z_]+\}\}/.test(html),'Unfilled template field');fs.writeFileSync(path.join(HERE,'index.html'),html);fs.writeFileSync(path.join(HERE,'timeline.json'),JSON.stringify(T,null,2)+'\n');}
function decode(p,filter=''){const argv=['-v','error','-i',p];if(filter)argv.push('-af',filter);argv.push('-ar',SR,'-ac','1','-f','f32le','-');const x=cp.spawnSync('ffmpeg',argv,{maxBuffer:100*1024*1024});need(x.status===0,`Audio decode: ${p}: ${x.stderr}`);return new Float32Array(x.stdout.buffer.slice(x.stdout.byteOffset,x.stdout.byteOffset+x.stdout.byteLength));}
function put(dst,src,at,srcA=0,srcB=src.length/SR,gain=1,fade=.03){const lo=Math.max(0,Math.round(srcA*SR)),hi=Math.min(src.length,Math.round(srcB*SR)),d=Math.round(at*SR),f=Math.round(fade*SR);for(let j=lo;j<hi;j++){const k=d+j-lo;if(k<0||k>=dst.length)continue;dst[k]+=src[j]*gain*Math.max(0,Math.min(1,(j-lo)/f,(hi-j-1)/f));}}
function wav(p,a){const h=Buffer.alloc(44),pcm=Buffer.alloc(a.length*2);h.write('RIFF',0);h.writeUInt32LE(36+pcm.length,4);h.write('WAVEfmt ',8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(1,22);h.writeUInt32LE(SR,24);h.writeUInt32LE(SR*2,28);h.writeUInt16LE(2,32);h.writeUInt16LE(16,34);h.write('data',36);h.writeUInt32LE(pcm.length,40);for(let i=0;i<a.length;i++)pcm.writeInt16LE(Math.round(Math.max(-1,Math.min(1,a[i]))*32767),2*i);fs.writeFileSync(p,Buffer.concat([h,pcm]));}
function audio(T){const n=Math.round(T.duration*SR),d=new Float32Array(n),m=new Float32Array(n),by=Object.fromEntries(T.segments.map(s=>[s.name,s])),events=[];const models=['cb.rnnn','sh.rnnn'].map(x=>path.join(REPO,'local/models/rnnoise',x));let chain='highpass=f=100:poles=2,afftdn=nr=18:nf=-45:tn=0,agate=threshold=0.025:ratio=3:range=0.1:attack=5:release=200:knee=4,equalizer=f=250:t=q:w=1.2:g=-2,equalizer=f=3000:t=q:w=1:g=2,deesser=i=0.3:m=0.5:f=0.5,acompressor=threshold=-20dB:ratio=2:attack=10:release=150,loudnorm=I=-16:TP=-1.5:LRA=11';if(models.every(fs.existsSync))chain='highpass=f=100:poles=2,arnndn=m=local/models/rnnoise/cb.rnnn,arnndn=m=local/models/rnnoise/sh.rnnn:mix=0.6,'+chain;
  const vach=decode(path.join(ROOT,'Audio/normalpart1.mp3'),chain),yash=decode(path.join(ROOT,'Audio/Normalpart6.mp3'),chain),vAt=by.bench.start-.068+4.83,yAt=by.yash_before_notification.start-.3705+1.48;put(d,vach,vAt,4.83,9.83);events.push([vAt,vAt+5,'Vachana']);put(d,yash,yAt,1.48,3.02);events.push([yAt,yAt+1.54,'Yash opening']);if(YASH_REPLY){const a=by.yash_app.start+slots.yash_app.ptt_down+.1-.12;put(d,yash,a,8.48,10.94);events.push([a,a+2.46,'Yash reply']);}
  const voice=JSON.parse(fs.readFileSync(path.join(REPO,'film/common/narration.json'))).voice;need(['david','vivek'].includes(voice),'Invalid narration voice');const nf=voice==='vivek'?path.join(RENDERS,'narration/vivek/N1.wav'):path.join(RENDERS,'scene2/narration/david/N1.wav');need(fs.existsSync(nf)||preview,`Missing narration: ${nf}`);if(fs.existsSync(nf)){const v=decode(nf).map(x=>x*10**(2/20)),a=T.narration_starts.N1;put(d,v,a);events.push([a,a+v.length/SR,'N1']);}
  for(const [name,at,db] of [['sent',by.send_fly.start,-10],['notify',by.yash_app.start+(slots.yash_app.banner_at??slots.yash_app.notification_at),-9],...(YASH_REPLY?[['sent',by.yash_app.start+slots.yash_app.sent_at,-10]]:[])]){const p=path.join(RENDERS,'sound',name+'.wav');need(fs.existsSync(p)||preview,`Missing sound: ${p}`);if(fs.existsSync(p)){const v=decode(p);put(d,v,at,0,v.length/SR,10**(db/20),.002);events.push([at,at+v.length/SR,name]);}}
  need(fs.existsSync(ttsFile)||preview,`Missing TTS: ${ttsFile}`);if(fs.existsSync(ttsFile)){const v=decode(ttsFile,'loudnorm=I=-16:TP=-1.5:LRA=11'),a=by.yash_app.start+slots.yash_app.play_at+.15;put(d,v,a);events.push([a,a+v.length/SR,'TTS']);}events.sort((a,b)=>a[0]-b[0]);fs.writeFileSync(path.join(OUT,'audio_events.txt'),events.map(e=>`${e[0].toFixed(3)} ${e[1].toFixed(3)} ${e[2]}`).join('\n')+'\n');wav(path.join(OUT,'scene2_dialogue_sfx.wav'),d);wav(path.join(OUT,'scene2_music.wav'),m);return path.join(OUT,'scene2_dialogue_sfx.wav');}
function main(){const P=prepare(),tts=Number(info(ttsFile).format.duration),T=timeline(tts,P.w),c=captions(T,tts);page(T,P,c);need(P.speed===26,'Walk speed changed unexpectedly');need(c.length===(YASH_REPLY?8:7)&&c.every(x=>x.start>=0&&x.end<=T.duration&&x.end>x.start),'Caption coverage/timing failed');mkdir(path.join(REPO,'results/F0020'));fs.writeFileSync(path.join(REPO,'results/F0020/captions_check.txt'),`captions: ${c.length}\nTTS: ${c.filter(x=>x.start>=T.segments.at(-1).start+slots.yash_app.play_at+.15).length}\nYASH_REPLY: ${YASH_REPLY}\n`);if(!args.has('--audio-only'))run('hyperframes.cmd',['check'],HERE);if(args.has('--prepare')||args.has('--page-only'))return;const stem=audio(T);if(args.has('--audio-only'))return;
  if(preview){const html=fs.readFileSync(path.join(HERE,'index.html'),'utf8').replace('data-width="1920" data-height="1080"','data-width="960" data-height="540"').replace('</style>','html,body{width:960px;height:540px}#root{width:1920px!important;height:1080px!important;transform:scale(.5);transform-origin:0 0}</style>'),temp=path.join(HERE,'index-preview540.html'),raw=path.join(OUT,'scene2_picture_540.mp4');fs.writeFileSync(temp,html);try{run('hyperframes.cmd',['render','-c','index-preview540.html','-q','draft','-f','30','-o',raw],HERE)}finally{fs.unlinkSync(temp)}const v=video(raw,T.duration-.1);need(v.width===960&&v.height===540,'Preview is not 540p');const out=path.join(REPO,'results/F0020/preview/scene2_v3a_540.mp4');mkdir(path.dirname(out));run('ffmpeg',['-v','error','-y','-i',raw,'-i',stem,'-map','0:v:0','-map','1:a:0','-c:v','libx264','-preset','fast','-b:v','1100k','-maxrate','1400k','-bufsize','2800k','-c:a','aac','-b:a','128k','-t',T.duration,out]);need(fs.statSync(out).size<10*1024*1024,'Preview exceeds 10 MB');}
  else{const raw=path.join(OUT,'scene2_picture.mp4');run('hyperframes.cmd',['render','-q','high','-f','30','-o',raw],HERE);video(raw,T.duration-.1);run('ffmpeg',['-v','error','-y','-i',raw,'-i',stem,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-t',T.duration,path.join(OUT,'scene2_v3a.mp4')]);}console.log(JSON.stringify({duration:T.duration,end_state:T.end_state,preview}));}
try{main()}catch(e){console.error(e.stack||e);process.exit(1)}
