/* Scene 2 v4a: node build.js [--prepare|--page-only|--audio-only|--preview|--render].
   Narration durations drive the Normal card and N1 beat. The app status mask is painted on the phone layer. */
const fs=require('fs'),path=require('path'),cp=require('child_process');
const HERE=__dirname,REPO=path.resolve(HERE,'../../..'),M=JSON.parse(fs.readFileSync(path.join(REPO,'machine.local.json')));
const ROOT=M.footage_root,RENDERS=M.renders_dir,OUT=path.join(path.resolve(REPO,process.env.S2A_RENDER_ROOT||RENDERS),'scene2/v3a'),A=path.join(HERE,'assets');
const FPS=30,SR=48000,YASH_REPLY=process.env.YASH_REPLY!=='false',args=new Set(process.argv.slice(2)),preview=args.has('--preview');
const slots=JSON.parse(fs.readFileSync(path.join(HERE,'slots.json'))),ttsFile=path.join(RENDERS,'tts_itantra/tts_msg.wav');
const need=(ok,msg)=>{if(!ok)throw Error(msg)},mkdir=p=>fs.mkdirSync(p,{recursive:true});
const RESULTS=path.join(REPO,'results/F0061');
/* Intro hand-off: s2a frame 0 = FOOTAGE:Video/normalpart1.mp4 at this source time (intro's last ~1 s shows it from 0). */
function introSrc(){try{const t=JSON.parse(fs.readFileSync(path.join(REPO,'film/intro_v3/timeline.json')));const v=t.end_state&&t.end_state.normalpart1_src;return typeof v==='number'?v:1.0}catch{return 1.0}}
const S0=introSrc();
/* Yash's app recording, played at 1x in pieces. Every cut sits inside a stretch with no on-screen change (checked with
   ffmpeg freezedetect at build time): banner hold 1.77-3.10, Logs 3.93-5.37, message screen 5.53-7.80,
   after playback 11.10-12.30, compose 16.50-19.00. The last piece ends at 19.467 so s2b's 1.4 s push-in continues the
   recording from there (sent tick -> Logs). Never sped up. */
const YASH_EDL=[[1.25,2.40],[2.90,3.95],[4.95,5.60],[7.20,11.30],[11.85,16.80],[18.30,19.4667]];
/* Yash camera (FOOTAGE:Video/normalpart6.mp4) windows in the split, in seconds of the yash_app segment. Camera source =
   clean audio - 0.37 s. Window A continues the full shot (source 2.65 at dt 0); window B is locked to his reply audio
   (source = dt + 0.90), so he is listening (source 4.33-7.67) while the app plays the message. No source is shown twice. */
const CAM_A={start:0,show_until:1.0,out:1.5,media:2.65},CAM_B={in:3.4,show_from:3.9,show_until:11.2,out:11.7,offset:0.90};
function run(exe,argv,cwd=REPO){const x=cp.spawnSync(exe,argv.map(String),{cwd,encoding:'utf8',shell:exe.endsWith('.cmd'),maxBuffer:64*1024*1024});need(!x.error&&x.status===0,`${exe}: ${x.error||''}\n${x.stderr||''}\n${x.stdout||''}`);return x.stdout;}
function info(p){need(fs.existsSync(p),`Missing asset: ${p}`);return JSON.parse(run('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_type,width,height','-of','json',p]));}
function video(p,len,portrait=false){const x=info(p),v=x.streams.find(s=>s.codec_type==='video');need(v&&Number(x.format.duration)+.08>=len&&v.width>=100&&v.height>=100&&(!portrait||v.height>v.width),`Bad video: ${p}`);return v;}
function fresh(p,s){return !fs.existsSync(p)||s.some(x=>fs.statSync(x).mtimeMs>fs.statSync(p).mtimeMs)}
function link(src,dst){mkdir(path.dirname(dst));if(fs.existsSync(dst))fs.unlinkSync(dst);try{fs.linkSync(src,dst)}catch{fs.copyFileSync(src,dst)}}
function still(src,dst,at,filter){if(fresh(dst,[src]))run('ffmpeg',['-v','error','-y','-ss',at,'-i',src,...(filter?['-vf',filter]:[]),'-frames:v','1','-q:v','3',dst]);}
function grade(){return fs.readFileSync(path.join(REPO,'film/scene1/grades.sh'),'utf8').match(/^GRADE_V1="(.*)"$/m)[1]}
function camera(file,out,len){const src=path.join(ROOT,'Video',file),dst=path.join(A,out);need(fs.existsSync(src),`Missing footage ${file}`);if(fresh(dst,[src,path.join(REPO,'film/scene1/grades.sh')]))run('ffmpeg',['-v','error','-y','-ss','0','-t',len,'-i',src,'-vf',`fps=30,scale=1920:1080:flags=lanczos,${grade()},format=yuv420p`,'-an','-c:v','libx264','-preset','fast','-crf','20','-movflags','+faststart',dst]);video(dst,len);return dst;}
function walk(){const src=path.join(ROOT,'Video/normalpart2.mp4'),ramp=path.join(REPO,'results/T0006/ramp.json'),dst=path.join(OUT,'walk.mp4');need(fs.existsSync(src)&&fs.existsSync(ramp),'Missing walk source or ramp');const pieces=JSON.parse(fs.readFileSync(ramp)).pieces;
  if(fresh(dst,[src,ramp,path.join(REPO,'film/scene1/grades.sh')])){const fc=pieces.map((p,i)=>`[0:v]trim=start=${p.src_start}:end=${p.src_end},setpts=(PTS-STARTPTS)/${p.speed},fps=30,scale=1920:1080,setsar=1[v${i}]`);fc.push(pieces.map((_,i)=>`[v${i}]`).join('')+`concat=n=${pieces.length}:v=1:a=0,${grade()},format=yuv420p[out]`);run('ffmpeg',['-v','error','-y','-i',src,'-filter_complex',fc.join(';'),'-map','[out]','-frames:v','180','-an','-c:v','libx264','-preset','fast','-crf','20',dst]);}
  video(dst,5.95);if(!fs.existsSync(path.join(A,'walk.mp4'))||fs.statSync(path.join(A,'walk.mp4')).size!==fs.statSync(dst).size)link(dst,path.join(A,'walk.mp4'));return {span:pieces.reduce((n,p)=>n+p.src_end-p.src_start,0),pieces};}
function slot(spec,name){need(spec.path.startsWith('RENDERS:'),'Slot must use RENDERS:');const rel=spec.path.slice(8).split('/');need(!rel.some(s=>s==='..'||s==='')&&!path.isAbsolute(rel.join('/')),'Unsafe slot path');const src=path.join(RENDERS,...rel),dst=path.join(A,name+'.mp4');need(fs.existsSync(src)||preview,`Missing required slot: ${spec.path}`);if(fs.existsSync(src)){video(src,spec.duration,true);if(!fs.existsSync(dst)||fs.statSync(dst).size!==fs.statSync(src).size)link(src,dst)}else run('ffmpeg',['-v','error','-y','-f','lavfi','-i',`color=c=0x101820:s=1080x2290:r=30:d=${spec.duration}`,'-an','-c:v','libx264','-preset','ultrafast',dst]);const v=video(dst,spec.duration,true);still(dst,path.join(A,name+'_first.jpg'),0);still(dst,path.join(A,name+'_last.jpg'),spec.duration-.08);return {video:`assets/${name}.mp4`,width:Math.round(1000*v.width/v.height),placeholder:!fs.existsSync(src)};}
function edlLength(){return YASH_EDL.reduce((n,[a,b])=>n+b-a,0)}
function appToDt(a){let t=0;for(const [s,e] of YASH_EDL){if(a>=s-1e-6&&a<=e+1e-6)return +(t+a-s).toFixed(4);t+=e-s;}throw Error(`yash_app time ${a} falls in a trimmed idle stretch`)}
function narrationLine(id){const p=path.join(REPO,'film/common/narration_v4.json');const L=JSON.parse(fs.readFileSync(p,'utf8')).lines[id];need(L,`narration_v4.json has no ${id}`);const rel=(L.file||'').replace(/^RENDERS:/,'');return {...L,path:path.join(RENDERS,...rel.split('/'))};}
function checkEdl(file){/* every internal cut must sit inside a stretch with no on-screen change */
  const x=cp.spawnSync('ffmpeg',['-hide_banner','-nostats','-i',file,'-vf','freezedetect=n=-60dB:d=0.2','-an','-f','null','-'],{encoding:'utf8',maxBuffer:64*1024*1024});
  const starts=[...x.stderr.matchAll(/freeze_start: ([\d.]+)/g)].map(m=>+m[1]),ends=[...x.stderr.matchAll(/freeze_end: ([\d.]+)/g)].map(m=>+m[1]);
  const ranges=starts.map((s,i)=>[s,ends[i]??Infinity]),cuts=YASH_EDL.flatMap(([a,b],i)=>[...(i?[a]:[]),...(i<YASH_EDL.length-1?[b]:[])]);
  const bad=cuts.filter(c=>!ranges.some(([s,e])=>c>=s-.02&&c<=e+.02));need(!bad.length,`yash_app cut points not in idle stretches: ${bad.join(', ')}`);return {cuts,ranges};}
function timeline(tts,w,n0,n1){const seg=[],add=(name,start,end,extra={})=>seg.push({name,start:+start.toFixed(3),end:+end.toFixed(3),...extra});
  const cardBeat=n0.duration+.4,benchEnd=cardBeat,benchSourceEnd=S0+benchEnd,vs=benchEnd+.5,send=vs+slots.vachana_send.sent_at,ws=send+.4,over=ws+6-.88;
  const n1Start=ws+.3,n1Beat=n1.duration+.4,overDuration=Math.max(5,n1Start+n1Beat-over),yash=over+overDuration,ya=yash+1.67,ye=ya+edlLength();
  need(benchSourceEnd+.5<10.83,'N0 card runs beyond the moving bench footage');
  add('bench',0,benchEnd,{source:'FOOTAGE:Video/normalpart1.mp4',source_in:S0,source_out:+benchSourceEnd.toFixed(4),intro_join:true});
  add('mode_card',0,cardBeat,{over:'bench',title:'Normal',subline:'a private message to someone you trust',narration:'N0'});
  add('vachana_split_in',benchEnd,vs,{source:'FOOTAGE:Video/normalpart1.mp4',source_in:+benchSourceEnd.toFixed(4),source_out:+(benchSourceEnd+.5).toFixed(4)});
  add('vachana_send',vs,send,{slot:'vachana_send',slot_in:0,slot_out:slots.vachana_send.sent_at,camera_source:'FOOTAGE:Video/normalpart1.mp4',camera_offset:+(benchSourceEnd+.5).toFixed(4),camera_visible_until:+(benchEnd+10.83-benchSourceEnd).toFixed(3)});
  add('send_fly',send,send+.8,{slot:'vachana_send',sent_at:+send.toFixed(3)});
  add('walk',ws,over,{source:'FOOTAGE:Video/normalpart2.mp4',source_ranges:w.pieces.map(p=>[p.src_start,p.src_end]),speed_factor:+(w.span/6).toFixed(3),overlap_with_flight:.4});
  add('overhead',over,yash,{walk_video_media_start:5.12,walk_video_duration:.88,yash_video_media_start:0,yash_video_starts_at:+(overDuration-.98).toFixed(3),yash_video_duration:.98,map_hold:+(overDuration-5).toFixed(3)});
  add('yash_before_notification',yash,ya,{source:'FOOTAGE:Video/normalpart6.mp4',source_in:.98,source_out:2.65});
  const ev={banner:appToDt(slots.yash_app.banner_at),play:appToDt(slots.yash_app.play_at),tts:appToDt(slots.yash_app.play_at+.15),ptt_down:appToDt(slots.yash_app.ptt_down),ptt_up:appToDt(slots.yash_app.ptt_up),sent:appToDt(slots.yash_app.sent_at)};
  let t0=0;const pieces=YASH_EDL.map(([a,b])=>{const p={src_in:a,src_out:b,dt:+t0.toFixed(4)};t0+=b-a;return p;});
  add('yash_app',ya,ye,{slot:'yash_app',edl:pieces,events_dt:ev,camera_source:'FOOTAGE:Video/normalpart6.mp4',camera_a:{dt:[CAM_A.start,CAM_A.out],media_in:CAM_A.media},camera_b:{dt:[CAM_B.in,CAM_B.out],media_in:+(CAM_B.in+CAM_B.offset).toFixed(3)},YASH_REPLY});
  const width=Math.round(1000*1080/2400);
  return {fps:FPS,duration:+ye.toFixed(3),intro_src:S0,segments:seg,narration_starts:{N0:0,N1:+n1Start.toFixed(3)},narration_durations:{N0:n0.duration,N1:n1.duration},narration_beats:{N0:+cardBeat.toFixed(3),N1:+n1Beat.toFixed(3)},slot_fields:{vachana_send:slots.vachana_send,yash_app:slots.yash_app},YASH_REPLY,
    end_state:{slot:'yash_app',slot_time:+(YASH_EDL.at(-1)[1]-1/FPS).toFixed(4),position:{x:(1920-width)/2,y:40,width,height:1000},background:'#0a0d12'}};}
function splitText(text){const w=text.split(/\s+/).filter(Boolean),h=Math.ceil(w.length/2);return [w.slice(0,h).join(' '),w.slice(h).join(' ')];}
function captions(T,tts,n0,n1){const p=path.join(REPO,'film/captions/v3/s2a.json');mkdir(path.dirname(p));const by=Object.fromEntries(T.segments.map(s=>[s.name,s])),ya=by.yash_app.start,ev=by.yash_app.events_dt,ns=T.narration_starts.N1,shift=by.vachana_send.start-3.8;
  // N1 caption text comes from narration_v4.json (filled from the real take); until then the v3 script line stands in.
  const n1text=(n1.text||'').trim()||"Let's see how far that message actually has to travel.",[l1,l2]=splitText(n1text),n1d=n1.duration;
  const c=[{start:0,end:n0.duration,text:n0.text},
    {start:4.882-S0+shift,end:8.202-S0+shift,text:"Hey dude, I'm in the campus\nnear the entry benches,"},{start:8.202-S0+shift,end:9.462-S0+shift,text:'where are you?'},
    {start:ns,end:ns+n1d*.48,text:l1},{start:ns+n1d*.48,end:ns+n1d,text:l2},
    {start:by.yash_before_notification.start+.13,end:by.yash_before_notification.start+1.67,text:"It's too hot here."},
    {start:ya+ev.tts,end:ya+ev.tts+tts*.55,text:"Hey dude, I'm in the campus\nnear the entry benches,"},{start:ya+ev.tts+tts*.55,end:ya+ev.tts+tts,text:'where are you?'}];
  if(YASH_REPLY)c.push({start:ya+ev.ptt_down-.02,end:ya+ev.ptt_down-.02+2.46,text:"I'm in the garden.\nI'll come to you."});
  const clean=c.map(x=>({start:+x.start.toFixed(3),end:+Math.min(x.end,T.duration).toFixed(3),text:x.text}));fs.writeFileSync(p,JSON.stringify(clean,null,2)+'\n');return clean;}
function prepare(){mkdir(A);mkdir(OUT);const b=camera('normalpart1.mp4','bench.mp4',10.83);camera('normalpart6.mp4','yash.mp4',12.647);const w=walk(),app={vachana_send:slot(slots.vachana_send,'vachana_send'),yash_app:slot(slots.yash_app,'yash_app')};
  still(b,path.join(A,'bench_start.jpg'),S0);still(path.join(A,'vachana_send.mp4'),path.join(A,'vachana_sent.jpg'),12.8);
  const kit=path.join(REPO,'film/common/glass');if(fs.existsSync(path.join(kit,'glass.css'))){mkdir(path.join(A,'glass'));for(const f of ['glass.css','glass.js','noise.png'])if(fs.existsSync(path.join(kit,f)))fs.copyFileSync(path.join(kit,f),path.join(A,'glass',f));}
  if(fs.existsSync(path.join(HERE,'overhead/overhead.js'))){const geo=path.join(REPO,'film/scene2/geo'),osm=path.join(geo,'nie_north_osm.json'),outlines=path.join(geo,'campus_outlines.json');need(fs.existsSync(osm)&&fs.existsSync(outlines),'Missing overhead campus geometry');fs.writeFileSync(path.join(A,'geo.js'),'window.OVERHEAD_GEO='+JSON.stringify({osm:JSON.parse(fs.readFileSync(osm)),outlines:JSON.parse(fs.readFileSync(outlines))})+';\n');}
  const edl=app.yash_app.placeholder?null:checkEdl(path.join(A,'yash_app.mp4'));
  return {app,w,edl,speed:Math.round(w.span/6),glass:fs.existsSync(path.join(A,'glass/glass.css')),overhead:fs.existsSync(path.join(HERE,'overhead/overhead.js'))};}
function page(T,P,c){let html=fs.readFileSync(path.join(HERE,'index.html.tpl'),'utf8');const by=Object.fromEntries(T.segments.map(s=>[s.name,s])),ya=by.yash_app,oh=by.overhead,yf=by.yash_before_notification,ws=by.walk,vs=by.vachana_send.start,benchEnd=by.bench.end,benchSrc=by.bench.source_out;
  const pieces=ya.edl.map((p,i)=>`<video id="yApp${i}" class="clip yapp" src="assets/yash_app.mp4" data-start="${+(ya.start+p.dt).toFixed(4)}" data-duration="${+(p.src_out-p.src_in).toFixed(4)}" data-media-start="${p.src_in}" muted playsinline></video>`).join('');
  const subs={TIMELINE:JSON.stringify(T),SLOTS:JSON.stringify(P.app),CAPTIONS:JSON.stringify(c),DURATION:T.duration,SPEED:P.speed,S0:S0,BENCH_DUR:benchEnd,VCAM_START:benchEnd,VCAM_MEDIA:benchSrc,VCAM_DUR:+(10.83-benchSrc).toFixed(3),VAPP_START:+vs.toFixed(3),
    WALK_START:ws.start,WALK_DURATION:+(ws.end-ws.start).toFixed(3),OVERHEAD_START:oh.start,OVERHEAD_WALK_START:5.12,OVERHEAD_YASH_START:+(oh.end-.98).toFixed(3),YASH_START:yf.start,YASH_FULL_DUR:+(yf.end-yf.start).toFixed(3),
    YAPP_PIECES:pieces,CAM_A_START:ya.start,CAM_A_DUR:CAM_A.out,CAM_A_MEDIA:CAM_A.media,CAM_B_START:+(ya.start+CAM_B.in).toFixed(3),CAM_B_DUR:+(CAM_B.out-CAM_B.in).toFixed(3),CAM_B_MEDIA:+(CAM_B.in+CAM_B.offset).toFixed(3),
    GLASS_LINK:P.glass?'<link rel="stylesheet" href="assets/glass/glass.css">':'',OVERHEAD_LINK:P.overhead?'<link rel="stylesheet" href="overhead/overhead.css"><script src="assets/geo.js"></script><script src="overhead/overhead.js"></script>':''};
  need(CAM_B.out+CAM_B.offset<=12.647,'Yash camera window B runs past the clip');need(CAM_A.media+CAM_A.out<=CAM_B.in+CAM_B.offset,'Yash camera windows would repeat footage');
  for(const [k,v] of Object.entries(subs))html=html.replaceAll('{{'+k+'}}',String(v));need(!/\{\{[A-Z0-9_]+\}\}/.test(html),'Unfilled template field');fs.writeFileSync(path.join(HERE,'index.html'),html);fs.writeFileSync(path.join(HERE,'timeline.json'),JSON.stringify(T,null,2)+'\n');}
function decode(p,filter=''){const argv=['-v','error','-i',p];if(filter)argv.push('-af',filter);argv.push('-ar',SR,'-ac','1','-f','f32le','-');const x=cp.spawnSync('ffmpeg',argv,{maxBuffer:100*1024*1024});need(x.status===0,`Audio decode: ${p}: ${x.stderr}`);return new Float32Array(x.stdout.buffer.slice(x.stdout.byteOffset,x.stdout.byteOffset+x.stdout.byteLength));}
function put(dst,src,at,srcA=0,srcB=src.length/SR,gain=1,fade=.03){const lo=Math.max(0,Math.round(srcA*SR)),hi=Math.min(src.length,Math.round(srcB*SR)),d=Math.round(at*SR),f=Math.round(fade*SR);for(let j=lo;j<hi;j++){const k=d+j-lo;if(k<0||k>=dst.length)continue;dst[k]+=src[j]*gain*Math.max(0,Math.min(1,(j-lo)/f,(hi-j-1)/f));}}
function wav(p,a){const h=Buffer.alloc(44),pcm=Buffer.alloc(a.length*2);h.write('RIFF',0);h.writeUInt32LE(36+pcm.length,4);h.write('WAVEfmt ',8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(1,22);h.writeUInt32LE(SR,24);h.writeUInt32LE(SR*2,28);h.writeUInt16LE(2,32);h.writeUInt16LE(16,34);h.write('data',36);h.writeUInt32LE(pcm.length,40);for(let i=0;i<a.length;i++)pcm.writeInt16LE(Math.round(Math.max(-1,Math.min(1,a[i]))*32767),2*i);fs.writeFileSync(p,Buffer.concat([h,pcm]));}
function audio(T,n0,n1){const n=Math.round(T.duration*SR),d=new Float32Array(n),m=new Float32Array(n),by=Object.fromEntries(T.segments.map(s=>[s.name,s])),ev=by.yash_app.events_dt,ya=by.yash_app.start,events=[];const models=['cb.rnnn','sh.rnnn'].map(x=>path.join(REPO,'local/models/rnnoise',x));let chain='highpass=f=100:poles=2,afftdn=nr=18:nf=-45:tn=0,agate=threshold=0.025:ratio=3:range=0.1:attack=5:release=200:knee=4,equalizer=f=250:t=q:w=1.2:g=-2,equalizer=f=3000:t=q:w=1:g=2,deesser=i=0.3:m=0.5:f=0.5,acompressor=threshold=-20dB:ratio=2:attack=10:release=150,loudnorm=I=-16:TP=-1.5:LRA=11';if(models.every(fs.existsSync))chain='highpass=f=100:poles=2,arnndn=m=local/models/rnnoise/cb.rnnn,arnndn=m=local/models/rnnoise/sh.rnnn:mix=0.6,'+chain;
  const vach=decode(path.join(ROOT,'Audio/normalpart1.mp3'),chain),yash=decode(path.join(ROOT,'Audio/Normalpart6.mp3'),chain);
  const vAt=4.83-.068-S0+(by.vachana_send.start-3.8),yAt=by.yash_before_notification.start+.13;put(d,vach,vAt,4.83,9.83);events.push([vAt,vAt+5,'dialogue Vachana']);put(d,yash,yAt,1.48,3.02);events.push([yAt,yAt+1.54,'dialogue Yash opening']);
  if(YASH_REPLY){const a=ya+ev.ptt_down-.02;put(d,yash,a,8.48,10.94);events.push([a,a+2.46,'dialogue Yash reply']);}
  const a0=T.narration_starts.N0;if(fs.existsSync(n0.path)){const v=decode(n0.path);put(d,v,a0);events.push([a0,a0+v.length/SR,'narration N0']);}else{need(preview||args.has('--page-only')||process.env.ALLOW_PLACEHOLDER_NARRATION==='1',`Missing narration: RENDERS:${path.relative(RENDERS,n0.path).split(path.sep).join('/')}`);events.push([a0,a0+n0.duration,'narration N0 (placeholder silence)']);}
  // N1 from narration_v4.json (duration-driven); a silent placeholder of that length if the take is not there yet.
  const a1=T.narration_starts.N1;if(fs.existsSync(n1.path)){const v=decode(n1.path);put(d,v,a1);events.push([a1,a1+v.length/SR,'narration N1']);}else{need(preview||args.has('--page-only')||process.env.ALLOW_PLACEHOLDER_NARRATION==='1',`Missing narration: RENDERS:${path.relative(RENDERS,n1.path).split(path.sep).join('/')}`);events.push([a1,a1+n1.duration,'narration N1 (placeholder silence)']);}
  for(const [name,at,db] of [['sent',by.send_fly.start,-10],['notify',ya+ev.banner,-9],...(YASH_REPLY?[['sent',ya+ev.sent,-10]]:[])]){const p=path.join(RENDERS,'sound',name+'.wav');need(fs.existsSync(p)||preview,`Missing sound: ${p}`);if(fs.existsSync(p)){const v=decode(p);put(d,v,at,0,v.length/SR,10**(db/20),.002);events.push([at,at+v.length/SR,'sfx '+name]);}}
  need(fs.existsSync(ttsFile)||preview,`Missing TTS: ${ttsFile}`);if(fs.existsSync(ttsFile)){const v=decode(ttsFile,'loudnorm=I=-16:TP=-1.5:LRA=11'),a=ya+ev.tts;put(d,v,a);events.push([a,a+v.length/SR,'TTS']);}
  events.sort((a,b)=>a[0]-b[0]);fs.writeFileSync(path.join(OUT,'audio_events.txt'),events.map(e=>`${e[0].toFixed(3)} ${e[1].toFixed(3)} ${e[2]}`).join('\n')+'\n');wav(path.join(OUT,'scene2_dialogue_sfx.wav'),d);wav(path.join(OUT,'scene2_music.wav'),m);return path.join(OUT,'scene2_dialogue_sfx.wav');}
function main(){const P=prepare(),tts=Number(info(ttsFile).format.duration),n0=narrationLine('N0'),n1=narrationLine('N1'),T=timeline(tts,P.w,n0,n1),c=captions(T,tts,n0,n1);page(T,P,c);
  need(P.speed===26,'Walk speed changed unexpectedly');need(c.length===(YASH_REPLY?9:8)&&c.every(x=>x.start>=0&&x.end<=T.duration&&x.end>x.start),'Caption coverage/timing failed');
  mkdir(RESULTS);fs.writeFileSync(path.join(RESULTS,'build_check.txt'),[`duration: ${T.duration}`,`intro_src (frame 0 source): ${S0}`,`YASH_REPLY: ${YASH_REPLY}`,`yash_app EDL (source s): ${JSON.stringify(YASH_EDL)}`,`yash_app events (segment dt): ${JSON.stringify(T.segments.find(s=>s.name==='yash_app').events_dt)}`,`EDL cuts checked against freezes: ${P.edl?P.edl.cuts.join(', '):'skipped (placeholder slot)'}`,`end_state: ${JSON.stringify(T.end_state)}`,`captions: ${c.length}`,`N0: ${n0.duration}s (${n0.status})`, `N1: ${n1.duration}s (${n1.status})`].join('\n')+'\n');
  if(!args.has('--audio-only'))run('hyperframes.cmd',['check'],HERE);if(args.has('--prepare')||args.has('--page-only'))return;const stem=audio(T,n0,n1);if(args.has('--audio-only'))return;
  if(preview){console.log('preview: use hyperframes.cmd snapshot for stills (no video render in this build).');}
  else{const raw=path.join(OUT,'scene2_picture.mp4');run('hyperframes.cmd',['render','-q','high','-f','30','-o',raw],HERE);video(raw,T.duration-.1);run('ffmpeg',['-v','error','-y','-i',raw,'-i',stem,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-t',T.duration,path.join(OUT,'scene2_v3a.mp4')]);}console.log(JSON.stringify({duration:T.duration,end_state:T.end_state,preview}));}
try{main()}catch(e){console.error(e.stack||e);process.exit(1)}
