<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=1920,height=1080">
<script src="./gsap.min.js"></script>{{GLASS_LINK}}{{OVERHEAD_LINK}}
<style>
@font-face{font-family:SceneSans;src:local('Segoe UI Variable')}*{box-sizing:border-box}html,body{margin:0;width:1920px;height:1080px;overflow:hidden;background:#0a0d12;color:#f6f7fa;font-family:SceneSans,'Segoe UI',sans-serif}
#root{position:relative;width:1920px;height:1080px;overflow:hidden;background:#0a0d12}video,img{display:block}.layer{position:absolute;inset:0;display:none;overflow:hidden}.full{position:absolute;inset:0;width:1920px;height:1080px;object-fit:cover}
#cardBg{filter:blur(18px) brightness(.55);transform:scale(1.06)}
.glass-card.full{position:absolute;inset:0;width:1920px;height:1080px;display:grid;place-items:center;background:rgba(13,20,29,.94);border:1px solid rgba(255,255,255,.16);box-shadow:inset 0 0 140px rgba(255,255,255,.025);backdrop-filter:blur(28px)}
#card{z-index:8;transform-origin:center center}.cardTitle{font-size:88px;font-weight:650;letter-spacing:-.025em;text-shadow:0 4px 22px #02060b}
.camera{position:absolute;left:0;top:0;width:1232px;height:1080px;overflow:hidden;background:#0a0d12}.camera video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center}.camera:after{content:'';position:absolute;right:0;top:0;width:24px;height:100%;background:linear-gradient(90deg,transparent,rgba(4,7,11,.85))}
.phone{position:absolute;top:40px;height:1000px;border-radius:32px;overflow:hidden;background:#0c131b;border:1px solid rgba(255,255,255,.14);box-shadow:0 22px 65px rgba(0,0,0,.65)}.phone video,.phone .screen-bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;background-size:cover;background-position:center}
#vScene,#yScene{position:absolute;inset:0;display:none;background:#0a0d12}#vScene .phone,#yScene .phone{z-index:2}#messageCard{position:absolute;z-index:6;width:470px;height:216px;overflow:hidden;border-radius:22px;padding:7px;background:rgba(34,51,65,.72);border:1px solid rgba(255,255,255,.34);box-shadow:0 16px 42px rgba(0,0,0,.6);display:none}#messageCard img{width:100%;height:100%;object-fit:cover;border-radius:15px}
#walkLabel{position:absolute;left:48px;bottom:92px;z-index:3}.label-pin{padding:13px 20px;border-radius:18px;background:rgba(10,22,31,.82);border:1px solid rgba(255,255,255,.23);font-size:27px;font-weight:600;box-shadow:0 8px 26px #0007}
#walk{z-index:2}
#overhead{position:absolute;inset:0;z-index:1;display:none;background:radial-gradient(ellipse at 52% 55%,#1a2934 0%,#101b25 45%,#0a0d12 90%);overflow:hidden}
#overheadFallback{position:absolute;inset:0}#overheadFallback:before{content:'';position:absolute;inset:15%;border:1px solid #5b7c8c44;transform:perspective(1400px) rotateX(25deg);background:repeating-linear-gradient(14deg,transparent 0 90px,#6c91a416 92px 94px),repeating-linear-gradient(101deg,transparent 0 115px,#6c91a414 117px 119px)}
#overhead .pin{position:absolute;top:52%;color:#eff8fb;font-size:30px}.pin:before{content:'';display:inline-block;width:14px;height:14px;border-radius:50%;background:#77bcee;box-shadow:0 0 24px #77bcee;margin-right:12px}#pinV{left:27%}#pinY{left:68%}#distance{position:absolute;left:50%;top:17%;transform:translateX(-50%);font-size:38px;white-space:nowrap}#overheadYash{position:absolute;inset:0;width:1920px;height:1080px;object-fit:cover;opacity:0}
.caption{position:absolute;z-index:20;left:50%;bottom:44px;transform:translateX(-50%);width:1120px;text-align:center;white-space:pre-line;font-size:43px;line-height:1.17;font-weight:600;color:#fff;text-shadow:0 2px 5px #000,0 4px 18px #000;background:rgba(5,10,15,.56);border-radius:18px;padding:10px 22px;display:none}.caption.side{left:55px;bottom:58px;transform:none;width:640px;font-size:37px}.caption.splitSide{left:75px;bottom:54px;transform:none;width:1080px;font-size:39px}
</style></head><body>
<div id="root" data-composition-id="scene2" data-start="0" data-duration="{{DURATION}}" data-width="1920" data-height="1080">
 <div class="layer" id="cardScene"><video id="cardBg" class="clip full" src="assets/bench.mp4" data-start="0" data-duration="1.6" data-media-start="0" muted playsinline></video></div>
 <div class="layer" id="bench"><video id="benchVideo" class="clip full" src="assets/bench.mp4" data-start="1.6" data-duration="4.3" data-media-start="0" muted playsinline></video></div>
 <div id="card" class="glass-card full"><div class="cardTitle">How the app works</div></div>
 <div id="vScene"><div class="camera"><video id="vCam" class="clip" src="assets/bench.mp4" data-start="5.9" data-duration="6.53" data-media-start="4.3" muted playsinline></video></div><div class="phone"><div class="screen-bg" style="background-image:url('assets/vachana_send_first.jpg')"></div><video id="vApp" class="clip" src="assets/vachana_send.mp4" data-start="6.4" data-duration="13.133" data-media-start="0" muted playsinline></video></div></div>
 <div id="messageCard" class="glass-panel"><img src="assets/message_crop.jpg" alt=""></div>
 <div class="layer" id="walk"><video id="walkVideo" class="clip full" src="assets/walk.mp4" data-start="18.78" data-duration="6" data-media-start="0" muted playsinline></video><div id="walkLabel" class="label-pin">Sped up {{SPEED}}×</div></div>
 <div id="overhead"><div id="overheadFallback"><div class="pin label-pin" id="pinV">Vachana</div><div class="pin label-pin" id="pinY">Yash</div><div id="distance" class="label-pin">~300 m, walking distance</div><img id="overheadYash" src="assets/yash_first.jpg" alt=""></div></div>
 <div class="layer" id="yashFull"><video id="yashFullVideo" class="clip full" src="assets/yash.mp4" data-start="29.78" data-duration="2.65" data-media-start="0" muted playsinline></video></div>
 <div id="yScene"><div class="camera"><video id="yEarly" class="clip" src="assets/yash.mp4" data-start="32.43" data-duration="4.45" data-media-start="2.65" muted playsinline></video>{{REPLY_VIDEO}}</div><div class="phone"><div class="screen-bg" style="background-image:url('assets/yash_app_first.jpg')"></div><video id="yApp" class="clip" src="assets/yash_app.mp4" data-start="32.43" data-duration="{{Y_APP_DUR}}" data-media-start="0" muted playsinline></video></div></div>
 <div id="caption" class="caption"></div>
</div>
<script>
const T={{TIMELINE}},S={{SLOTS}},C={{CAPTIONS}},by=Object.fromEntries(T.segments.map(x=>[x.name,x]));const el=id=>document.getElementById(id),clamp=x=>Math.max(0,Math.min(1,x)),ease=gsap.parseEase('power2.inOut');
const v=el('vScene'),y=el('yScene'),vp=v.querySelector('.phone'),yp=y.querySelector('.phone');vp.style.width=S.vachana_send.width+'px';yp.style.width=S.yash_app.width+'px';
let mounted=false;function mountOverhead(){if(mounted||!window.Overhead)return;window.Overhead.mount(el('overhead'),{walkStill:'assets/walk_last.jpg',yashStill:'assets/yash_first.jpg',geo:window.OVERHEAD_GEO});mounted=true;}
function phone(scene,p,dt,camEnd,reply){const cam=scene.querySelector('.camera'),entry=ease(clamp((dt+(scene===v?.5:0))/.5)),leave=ease(clamp((dt-camEnd)/.5)),back=reply?ease(clamp((dt-11.1)/.5))*(1-ease(clamp((dt-16.147)/.5))):0;
 const show=Math.min(1,1-leave+back);cam.style.width=(1920-688*entry)+'px';cam.style.transform=`translateX(${-1232*(1-show)}px)`;cam.style.opacity=show;
 const width=parseFloat(p.style.width),right=1232+(688-width)/2,centre=(1920-width)/2,x=centre+(right-centre)*show;p.style.left=x+'px';p.style.transform=`translateX(${688*(1-entry)}px)`;p.style.opacity=entry;}
function render(t){const card=el('card'),cs=el('cardScene'),b=el('bench'),w=el('walk'),oh=el('overhead'),yf=el('yashFull'),mc=el('messageCard');for(const x of [cs,b,w,oh,yf,v,y])x.style.display='none';mc.style.display='none';
 if(t<by.card_out.end){cs.style.display='block';card.style.display='grid';const q=ease(clamp((t-.05)/1.55));card.style.transform=`translate(${(-690*q)}px,${(-170*q)}px) scale(${1-.67*q})`;card.style.opacity=1-q;card.style.borderRadius=(36*q)+'px';}else{card.style.display='none';if(t<by.vachana_split_in.start)b.style.display='block';}
 if(t>=by.vachana_split_in.start&&t<by.walk.start){v.style.display='block';const dt=t-by.vachana_send.start,cam=v.querySelector('.camera');phone(v,vp,dt,5.53,false);cam.style.width=(1920-688*ease(clamp((t-by.vachana_split_in.start)/.5)))+'px';el('vCam').style.display=t<by.vachana_send.start+6.03?'block':'none';el('vApp').style.display=t>=by.vachana_send.start?'block':'none';v.querySelector('.screen-bg').style.backgroundImage=t<by.vachana_send.start?"url('assets/vachana_send_first.jpg')":"url('assets/vachana_send_last.jpg')";}
 if(t>=by.send_fly.start&&t<by.send_fly.end){const q=ease(clamp((t-by.send_fly.start)/.8));mc.style.display='block';mc.style.left=(740+1510*q)+'px';mc.style.top=(405-165*Math.sin(Math.PI*q))+'px';mc.style.transform=`rotate(${-8+14*q}deg) scale(${1-.34*q})`;}
 if(t>=by.walk.start&&t<by.walk.end){w.style.display='block';const dt=t-by.walk.start,enter=ease(clamp(dt/.4)),lift=ease(clamp((dt-5.4)/.6));w.style.transform=`translateX(${-1920*(1-enter)}px) perspective(1800px) rotateX(${22*lift}deg) scale(${1-.38*lift})`;w.style.opacity=1-lift;}
 if(t>=by.overhead.start-.6&&t<by.overhead.end){oh.style.display='block';mountOverhead();const dt=Math.max(0,t-by.overhead.start);if(mounted)window.Overhead.render(dt);else{const a=el('overheadYash'),q=ease(clamp((dt-4.4)/.6));a.style.opacity=q;a.style.transform=`scale(${1.18-.18*q})`;el('overheadFallback').style.opacity=1;}}
 if(t>=by.yash_before_notification.start&&t<by.yash_before_notification.end)yf.style.display='block';
 if(t>=by.yash_app.start&&t<by.yash_app.end){y.style.display='block';const dt=t-by.yash_app.start;phone(y,yp,dt,3.95,T.YASH_REPLY);el('yEarly').style.display=dt<4.45?'block':'none';if(T.YASH_REPLY)el('yReply').style.display=dt>=11.1&&dt<16.647?'block':'none';el('yApp').style.display='block';}
 const cap=C.find(c=>t>=c.start&&t<c.end),ce=el('caption');ce.style.display=cap?'block':'none';ce.textContent=cap?.text||'';ce.className='caption'+(cap&&t>=by.yash_app.start+4.45?' side':cap&&t>=by.vachana_split_in.start&&t<by.walk.start?' splitSide':'');}
const tl=gsap.timeline({paused:true,onUpdate:()=>render(tl.time())});tl.to({}, {duration:T.duration},0);window.addEventListener('hf-seek',e=>render(e.detail.time));window.__timelines=window.__timelines||{};window.__timelines.scene2=tl;render(0);
</script></body></html>
