<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<!-- GENERATED by film/scene2/sonar/build.py from shared/sonar.html.tpl. Edit the template, not this file. -->
<script src="./gsap.min.js"></script>
<script src="./three.min.js"></script>
<script src="./geo.js"></script>
<script src="./sonar.js"></script>
<script src="./overlay.js"></script>
<link rel="stylesheet" href="./sonar.css" />
<style>
  #black { position: absolute; inset: 0; background: #000; opacity: 0; }
</style>
</head>
<body>
<div id="root" data-composition-id="{{SEG}}" data-start="0" data-duration="{{DUR}}" data-width="1920" data-height="1080">
  <canvas id="sonar" width="1920" height="1080" data-layout-allow-overflow></canvas>
  <div id="ov"></div>
  <div id="black"></div>
  <audio id="sfx" class="clip" src="assets/{{SEG}}_sfx.wav" data-start="0" data-duration="{{DUR}}" data-volume="1"></audio>
</div>

<script>
  // All times come from film/scene2/sonar/cues.py (filled in by build.py).
  const CFG = {{CFG}};
  const U = window.SonarUtil, E = U.ease;
  const sonar = window.Sonar(document.getElementById('sonar'), window.GEO);
  const ov = window.SonarOverlay(document.getElementById('ov'), sonar, CFG.points);
  const OVW = CFG.overview;
  const pulses = CFG.pulses.map(p => ({ x: p[0][0], y: p[0][1], t0: p[1], speed: p[2] }));

  function camAt(t) {
    if (CFG.mode === 'a') {
      // slow glide from high and turned, settling on the overview (the frame every relay dive starts from)
      const f = E.sine(U.span(t, 0, CFG.cam_settle));
      return U.lerpCam(CFG.cam_start, OVW, f, E.inOut(U.span(t, 0, CFG.cam_settle)));
    }
    // sonar_b: the overview with a barely-there drift that comes to rest before the still ending
    const f = E.sine(U.span(t, 0, CFG.still_from));
    return U.lerpCam(CFG.cam_start, OVW, f);
  }

  function draw(t) {
    const tt = CFG.still_from != null ? Math.min(t, CFG.still_from) : t;     // true still frame at the end of sonar_b
    const fade = CFG.mode === 'a' ? E.sine(U.span(t, CFG.fade_in[0], CFG.fade_in[1])) : 1;
    const ringFade = CFG.ring_out ? 1 - E.sine(U.span(tt, CFG.ring_out[0], CFG.ring_out[1])) : 1;
    sonar.render(tt, { cam: camAt(tt), pulses, fade, ringFade, floor: CFG.floor });
    ov.update({ t: tt, on: CFG.points_on || {}, labelsOn: CFG.labels_on, idle: tt, hops: CFG.hops, arriveAt: CFG.arrive, visible: 1 });
  }

  const tl = gsap.timeline({ paused: true, onUpdate: () => draw(tl.time()) });
  tl.to({}, { duration: {{DUR}} }, 0);
  window.addEventListener('hf-seek', e => draw(e.detail.time));
  window.__timelines = window.__timelines || {};
  window.__timelines['{{SEG}}'] = tl;
  draw(0);
</script>
</body>
</html>
